### ISSUE TITLE
IllegalStateException: Expected a string but was BEGIN_ARRAY at line 5 column 15 path $.error.param

### ISSUE THREAD

**Issue by kasecato** [payjp/payjp-java#15]
- Version: 0.3.0
- OS Version: macOS Mojave

Steps to Reproduce:

1. Token.create(tokenParams)
    - tokenParams
        - "number": "4012888888881881"
        - "cvc": "111"
        - "exp_month": "12"
        - "exp_year": "2050"

```bash
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 5 column 15 path $.error.param

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at jp.pay.net.LivePayjpResponseGetter.handleAPIError(LivePayjpResponseGetter.java:510)
	at jp.pay.net.LivePayjpResponseGetter._request(LivePayjpResponseGetter.java:371)
	at jp.pay.net.LivePayjpResponseGetter.request(LivePayjpResponseGetter.java:70)
	at jp.pay.net.APIResource.request(APIResource.java:144)
	at jp.pay.model.Token.create(Token.java:107)
	at jp.pay.model.Token.create(Token.java:95)
```

**Comment by yatatsu** [comment]
@kasecato
Thanks for your feedback. 
We had reproduced the issue. It was caused by unexpected response in specific error response from API.
We have just fixed response.

**Comment by kasecato** [comment]
@yatatsu Thanks for your quick response 🎉🎉
