### ISSUE TITLE
API call fails with live API key

### ISSUE THREAD

**Issue by yusuke** [payjp/payjp-java#9]
Making API calls with live API key fail with the following stack trace:

> java.lang.IllegalArgumentException: Illegal character(s) in message header value: Basic ****************************************************************************
> ***********=
> 	at sun.net.www.protocol.http.HttpURLConnection.checkMessageHeader(HttpURLConnection.java:508)
> 	at sun.net.www.protocol.http.HttpURLConnection.isExternalMessageHeaderAllowed(HttpURLConnection.java:459)
> 	at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(HttpURLConnection.java:3018)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestProperty(HttpsURLConnectionImpl.java:316)
> 	at jp.pay.net.LivePayjpResponseGetter.createPayjpConnection(LivePayjpResponseGetter.java:150)
> 	at jp.pay.net.LivePayjpResponseGetter.createPostConnection(LivePayjpResponseGetter.java:177)
> 	at jp.pay.net.LivePayjpResponseGetter.makeURLConnectionRequest(LivePayjpResponseGetter.java:282)
> 	at jp.pay.net.LivePayjpResponseGetter.getPayjpResponse(LivePayjpResponseGetter.java:404)
> 	at jp.pay.net.LivePayjpResponseGetter._request(LivePayjpResponseGetter.java:354)
> 	at jp.pay.net.LivePayjpResponseGetter.request(LivePayjpResponseGetter.java:71)
> 	at jp.pay.net.APIResource.request(APIResource.java:144)
> 	at jp.pay.model.Charge.create(Charge.java:242)
> 	at jp.pay.model.Charge.create(Charge.java:194)

**Comment by yusuke** [comment]
It seems that LivePayjpResponseGetter#encodeString inserts line breaks as per MIME specification when the API key is long enough.
But HttpURLConnection doesn't accept header values containing any line break.
